ChampWebApp/Controllers/ChampController.cs
using AutoMapper;
using ChampWebApp.Abstractions.Repositories;
using ChampWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace ChampWebApp.Controllers;

public class ChampController:Controller
{
    private readonly IMapper _mapper;
	
    private readonly IUnitOfWorkRepository _repos;

    public ChampController(IMapper mapper,IUnitOfWorkRepository repos)
    {
        _mapper = mapper;
        _repos = repos;
    }
    
    [HttpGet]
    [Authorize("Create")]
    public IActionResult Create()
    {
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> Create(string name)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }
        
        await _repos.GenericRepository<Tournament>().CreateAsync(new Tournament()
        {
            Name = name
        });
        
        return RedirectToAction("Create");
    }

    public async Task<IActionResult> Info(int id)
    {
        var tournament = await _repos.GenericRepository<Tournament>()
            .FindAsync(t=>t.Id==id,relatedData:"LeagueSummaries.Command");
        
        return View(tournament);
    }
}

ChampWebApp/Views/Champ/Create.cshtml
@model Tournament


<form asp-action="Create" asp-controller="Champ" class="row justify-content-center" style="margin:180px auto;">
    <div class="col-auto">
        <input type="text" placeholder="Tournament name" id="inputPassword5" class="form-control" aria-labelledby="passwordHelpBlock">
        <div id="passwordHelpBlock" class="form-text">
            <span asp-validation-for="Name"></span>
        </div>
        <button type="submit" class="btn btn-primary form-control mt-3">Create</button>
         <a href="" class="btn btn-secondary mt-3 form-control">Add commands to this tournament</a>
    </div>
</form>

ChampWebApp/Views/Champ/Info.cshtml
@using ChampWebApp.Views.Shared.Components
@model Tournament


<div class="center" style="text-align: center">
    @(await Html.RenderComponentAsync<TournamentInfo>(RenderMode.ServerPrerendered, new {Tournament=Model}))
</div>