ChampWebApp/Models/Command.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;

namespace ChampWebApp.Models;

public class Command
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required] 
    public string Name { get; set; } = string.Empty;

    public Country Country { get; set; } = null!;
    
    public int CountryId { get; set; }
    
    public int UefaRanking { get; set; }
    
    public string? HomeStadium { get; set; }

    public bool IsActiveCommand { get; set; } = true;
    
    public Coach? Coach { get; set; }
    public ICollection<Player> Players { get;}
    public ICollection<StageGroup> StageGroups { get; }
    public ICollection<LeagueSummary> LeagueSummaries { get;}
    public ICollection<MatchEvent> MatchEvents { get;}
    public ICollection<MatchStatistic> MatchStatistics { get;}

    public Command()
    {
        StageGroups = new List<StageGroup>();
        LeagueSummaries = new List<LeagueSummary>();
        MatchEvents = new List<MatchEvent>();
        MatchStatistics = new List<MatchStatistic>();
        Players = new List<Player>();
    }
}

ChampWebApp/Controllers/CommandController.cs
using AutoMapper;
using ChampWebApp.Abstractions.Repositories;
using ChampWebApp.Models;
using ChampWebApp.Models.Dtos.Input;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ChampWebApp.Controllers;

public class CommandController:Controller
{
	private readonly IMapper _mapper;
	
	private readonly IUnitOfWorkRepository _repos;
	
	public CommandController(IUnitOfWorkRepository uof,IMapper mapper)
	{
		_repos = uof;
		_mapper = mapper;
	}
	public async Task<IActionResult> Index()
	{
		var commands = await _repos.GenericRepository<Command>().GetAsync(includeProperties:"Coach,Country");
		
		
		
		return View(commands);
	}
	
	[HttpGet]
	public IActionResult Create()
	{
		return View();
	}
	
	[HttpPost]
	public async Task<IActionResult> Create(CommandInputDto command)
	{
		if (!ModelState.IsValid)
		{
			return View();
		}

		var model = _mapper.Map<Command>(command);
		await _repos.GenericRepository<Command>().CreateAsync(model);
		if (command.CoachId!=null)
		{
			var coaches = await _repos.GenericRepository<Coach>().GetAsync(filter: c => c.Id == command.CoachId);
			var coach = coaches.FirstOrDefault();
			if (coach != null){ model.Coach = coach;}
		}
		await _repos.SaveAsync();
		TempData["SuccessMessage"] = "Command created!";
		return RedirectToAction("Create");
	}
}

ChampWebApp/Pages/CountryListViewComponent.cs
using ChampWebApp.Abstractions.Repositories;
using ChampWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace ChampWebApp.Pages;


public class CountryListViewComponent : ViewComponent
{
    private readonly IUnitOfWorkRepository _repos;
    
    public CountryListViewComponent(IUnitOfWorkRepository uow)
    {
        _repos = uow;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var countries = await _repos.GenericRepository<Country>().GetAsync();
        return View(countries);
    }
}

ChampWebApp/Views/Command/Create.cshtml
@model ChampWebApp.Models.Dtos.Input.CommandInputDto

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success" id="success">@TempData["SuccessMessage"]</div>
}

<form asp-action="Create" asp-controller="Command" class="col-form" id="form">
    <input type="text" class="input" asp-for="Name" autocomplete="off" placeholder="Command name">
    <input type="number" class="input" asp-for="UefaRanking" autocomplete="off" placeholder="Uefa Ranking">
    <input type="text" class="input" asp-for="HomeStadium" autocomplete="off" placeholder="Home Stadium">
    @await Component.InvokeAsync("CountryList")
    <div>
        <span class="btn btn-light">Coach:</span>
        <span id="selected-coach" class="btn btn-light">Not selected</span>
        <button type="button" id="browse" class="btn btn-warning text-decoration-none">Browse coaches</button>
    </div>
    <input type="hidden" name="CoachId">
    <input type='submit' value="create" class="btn btn-primary text-decoration-none">
</form>


<div class="coach-menu" id="coach-menu"></div>

<script src="~/js/coachMenu.js" defer></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" defer>

ChampWebApp/Views/Command/Index.cshtml
@model IEnumerable<Command>

<link rel="stylesheet" href="~/css/command.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" defer>

@if (@Model.Any())
{
    <div class="filter-wrapper">

        <span class="btn btn-light">Sort by:</span>
        <select id="sort-by" class="input">
            <option value="name" selected>Name</option>
            <option value="uefaRanking">Rank</option>
            <option value="country_name">Country</option>
            <option value="coach_name">Coach</option>
        </select>


        <select id="sort-mode" class="input">
            <option value="ASC" selected>Ascending</option>
            <option value="DESC">Descending</option>
        </select>
        
        <div class="btn btn-light">Accumulation:</div>
        <i class="bi bi-check-lg clickable hover-green" id="acc" style="font-size: 30px"></i>
    </div>
    <table>
        <thead>
        <tr>
            <th>Name</th>
            <th>Uefa rank</th>
            <th>Country</th>
            <th>Coach</th>
        </tr>
        </thead>
        <tbody id="content">
        @foreach (var c in @Model)
        {
            <tr>
                <td>@c.Name</td>
                <td>@c.UefaRanking</td>
                <td>@c.Country.Name</td>
                @if (@c.Coach != null)
                {
                    <td>@c.Coach.FullName</td>
                }
                else
                {
                    <td>Absent</td>
                }
            </tr>
        }
        </tbody>
    </table>

    <a asp-controller="Command" asp-action="Create">Create command</a>
}
else
{
    <div>Commands list is empty, <a asp-controller="Command" asp-action="Create">you can add it here</a></div>
}

<script src="~/js/filtering.js" defer></script>